sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/DEV_Widget__c.object-meta.xml
<CustomObject>
    <label>Widget</label>
    <nameField>
        <displayFormat>Widget-{000000000}</displayFormat>
        <label>Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_Cost__c.field-meta.xml
<CustomField>
    <fullName>DEV_Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_Description__c.field-meta.xml
<CustomField>
    <fullName>DEV_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_FacetCount__c.field-meta.xml
<CustomField>
    <fullName>DEV_FacetCount__c</fullName>
    <label>Facet Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_IsScrap__c.field-meta.xml
<CustomField>
    <fullName>DEV_IsScrap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Scrap</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_ManufacturedDate__c.field-meta.xml
<CustomField>
    <fullName>DEV_ManufacturedDate__c</fullName>
    <label>Manufactured Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_SerialGuid__c.field-meta.xml
<CustomField>
    <fullName>DEV_SerialGuid__c</fullName>
    <label>Serial Guid</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_SoldTo__c.field-meta.xml
<CustomField>
    <fullName>DEV_SoldTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Widgets</relationshipLabel>
    <relationshipName>Widgets</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/at4dx-playground/main/schema/objects/DEV_Widget__c/fields/DEV_Status__c.field-meta.xml
<CustomField>
    <fullName>DEV_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Designed</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
            <value>
                <fullName>Tested</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
            </value>
            <value>
                <fullName>Alloted</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/at4dx-playground/main/classes/selectors/DEV_WidgetsSelector.cls
public virtual inherited sharing class DEV_WidgetsSelector
	extends ApplicationSObjectSelector
	implements DEV_IWidgetsSelector
{
	public static DEV_IWidgetsSelector newInstance()
	{
		return (DEV_IWidgetsSelector) Application.Selector.newInstance(DEV_Widget__c.SObjectType);
	}

	public virtual SObjectType getSObjectType()
	{
		return DEV_Widget__c.SObjectType;
	}

	public override virtual List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			DEV_Widget__c.Id,
			DEV_Widget__c.Name,
			DEV_Widget__c.DEV_Cost__c,
			DEV_Widget__c.DEV_Description__c,
			DEV_Widget__c.DEV_FacetCount__c,
			DEV_Widget__c.DEV_IsScrap__c,
			DEV_Widget__c.DEV_ManufacturedDate__c,
			DEV_Widget__c.DEV_SerialGuid__c,
			DEV_Widget__c.DEV_SoldTo__c,
			DEV_Widget__c.DEV_Status__c
		};
	}

	private virtual List<Schema.SObjectField> getAdditionalSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
			// Add desired fields; typically lookups to other SObjects
		};
	}

	public virtual List<DEV_Widget__c> selectById(Set<Id> idSet)
	{
		return (List<DEV_Widget__c>) selectSObjectsById( idSet == null ? new Set<Id>() : idSet );
	}

	public virtual List<DEV_Widget__c> selectByMixedArguments(Set<String> guidSetA, Set<String> guidSetB, Set<DEV_WidgetEnums.StateEnum> enumSet)
	{
		return null;
	}
}